import "@/styles/globals.css"
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client"
import Head from "next/head"

import { MoralisProvider } from "react-moralis"


export default function App({ Component, pageProps }) {
    const client = new ApolloClient({
        cache: new InMemoryCache(),
        uri: "https://api.studio.thegraph.com/query/41318/blocksocial/v0.0.5",
    })
    return (
        <div>
            <Head>
                <title>Block Social</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MoralisProvider initializeOnMount={false}>
                <ApolloProvider client={client}>
                    <Component {...pageProps} />
                </ApolloProvider>
            </MoralisProvider>
        </div>
    )
}
