import "@/styles/globals.css"
import "@/styles/loadingStyle.css"

import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client"
import Head from "next/head"
import React from "react"

import { MoralisProvider } from "react-moralis"
import { NotificationProvider } from "web3uikit"

import { toast, ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

export const apolloClient = new ApolloClient({
    cache: new InMemoryCache(),
    uri: "https://api.studio.thegraph.com/query/41318/blocksocial/v0.1",
})

export default function App({ Component, pageProps }) {
    return (
        <>
            <ToastContainer
                position={toast.POSITION.BOTTOM_LEFT}
                theme="dark"
            />
            <Head>
                <title>Block Social</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/icon.png" />
            </Head>

            <MoralisProvider initializeOnMount={false}>
                <ApolloProvider client={apolloClient}>
                    <NotificationProvider>
                        <Component {...pageProps} />
                    </NotificationProvider>
                </ApolloProvider>
            </MoralisProvider>
        </>
    )
}
